# Generated by Django 5.1.3 on 2024-11-15 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateField(blank=True, max_length=30, null=True)),
                ('Reply', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateField(blank=True, max_length=30, null=True)),
                ('Review', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Details', models.TextField(blank=True, max_length=30, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpareBookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpareName', models.CharField(blank=True, max_length=30, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpareTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spare_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Details', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Spare_add',
        ),
        migrations.DeleteModel(
            name='Sparebooking',
        ),
        migrations.RenameField(
            model_name='stationtable',
            old_name='VehicleNumber',
            new_name='StationNumber',
        ),
        migrations.AddField(
            model_name='servicetable',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationtable',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertable',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INSTITUTE', 'Institute'), ('TEACHER', 'Teacher')], max_length=20),
        ),
        migrations.AddField(
            model_name='complainttable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.usertable'),
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.usertable'),
        ),
        migrations.AddField(
            model_name='slottable',
            name='STATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.stationtable'),
        ),
        migrations.AddField(
            model_name='sparebookingtable',
            name='SLOT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.slottable'),
        ),
        migrations.AddField(
            model_name='sparebookingtable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.usertable'),
        ),
        migrations.AddField(
            model_name='sparetable',
            name='STATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.stationtable'),
        ),
    ]
