# Generated by Django 5.1.3 on 2025-01-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0004_remove_sparetable_spare_name_sparetable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationtable',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='Address',
        ),
        migrations.AddField(
            model_name='stationtable',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationtable',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
