# Generated by Django 5.1.3 on 2025-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0005_remove_stationtable_address_remove_usertable_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='longitude',
        ),
        migrations.AddField(
            model_name='usertable',
            name='Address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
