# Generated by Django 5.1.4 on 2025-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0007_complainttable_category_complainttable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='Complaint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='Reply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
