# Generated by Django 5.1.4 on 2025-01-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0008_alter_complainttable_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.logintable'),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.logintable'),
        ),
    ]
