# Generated by Django 5.1.4 on 2025-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0009_alter_complainttable_user_alter_feedbacktable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
