# Generated by Django 5.1.4 on 2025-01-05 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0010_alter_feedbacktable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='Chargingstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evapp.servicetable'),
        ),
    ]
