# Generated by Django 5.1.4 on 2025-01-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0011_feedbacktable_chargingstation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='Review',
            new_name='Rate',
        ),
    ]
