# Generated by Django 5.1.4 on 2025-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0012_rename_review_feedbacktable_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
