# Generated by Django 5.1.4 on 2025-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0013_alter_feedbacktable_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Rate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
