# Generated by Django 5.1.4 on 2025-01-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0014_alter_feedbacktable_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Chargingstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evapp.stationtable'),
        ),
    ]
