# Generated by Django 5.1.4 on 2025-01-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0015_alter_feedbacktable_chargingstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.usertable'),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evapp.usertable'),
        ),
    ]
