# Generated by Django 5.1.4 on 2025-01-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0016_alter_complainttable_user_alter_feedbacktable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparetable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='spare/'),
        ),
    ]
