# Generated by Django 5.1.4 on 2025-01-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0017_sparetable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparetable',
            name='STATION',
        ),
        migrations.AddField(
            model_name='sparetable',
            name='SERVICE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evapp.servicetable'),
        ),
    ]
