# Generated by Django 5.1.4 on 2025-01-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0019_remove_sparebookingtable_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparebookingtable',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='sparebookingtable',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='sparebookingtable',
            name='SpareName',
        ),
    ]
