# Generated by Django 5.1.4 on 2025-01-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0020_remove_sparebookingtable_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slottable',
            name='Details',
        ),
        migrations.RemoveField(
            model_name='slottable',
            name='Name',
        ),
        migrations.AddField(
            model_name='slottable',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evapp.usertable'),
        ),
        migrations.AlterField(
            model_name='slottable',
            name='STATION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evapp.stationtable'),
        ),
    ]
