# Generated by Django 5.1.4 on 2025-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0021_remove_slottable_details_remove_slottable_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alert', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
