# Generated by Django 5.1.4 on 2025-01-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0025_alter_slottable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtable',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='servicetable',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
